---
# tasks file for isweluiz.ansible-package-manage

- block: 
    - name: "Install :: Package list to install" 
      debug:
        msg: "Package list that should be installed: {{ base_system_packages_install }}"

    - name: "Install :: Check if listed package is installed or not"
      command: dpkg-query -l "{{ item }}"
      loop: 
        - "{{ base_system_packages_install }}"
      register: base_package_check
      changed_when: false
      ignore_errors: true

    - name: "Install :: Update apt cache"
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: "Install :: Installing Package List"
      package: 
        name: "{{ item }}" 
        state: present
      with_items:
        - "{{ base_system_packages_install }}"
      become: true
      when: base_package_check is failed
  tags: 
    - install
