---
# tasks file for  isweluiz.ansible-package-manage

- block: 
    - name: "Remove :: Package list to remove" 
      debug:
        msg: "Package list that should be removed: {{ base_system_packages_remove }}"

    - name: "Remove :: Check if listed package is installed or not"
      command: dpkg-query -l "{{ item }}"
      loop: 
        - "{{ base_system_packages_remove }}"
      register: base_package_check
      changed_when: false
      ignore_errors: true

    - name: "Remove :: Removing Package List"
      package: 
        name: "{{ item }}" 
        state: absent
      with_items:
        - "{{ base_system_packages_remove }}"
      become: true
      when: base_package_check is succeeded
  tags: 
    - remove
