---
# tasks file for  isweluiz.ansible-package-manage

- block: 
    - name: "Update :: Package list to Update" 
      debug:
        msg: "Package list that should be removed: {{ base_system_packages_update }}"

    - name: "Update :: Check if listed package is installed or not"
      command: dpkg-query -l "{{ item }}"
      loop: 
        - "{{ base_system_packages_update }}"
      register: base_package_check
      changed_when: false

    - name: "Update :: Updating package list to the latest version"
      package: 
        name: "{{ item }}" 
        state: latest
      with_items:
        - "{{ base_system_packages_update }}"
      become: true
      when: base_package_check is succeeded
  tags: 
    - update
